server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: /Users/redarqas/projects/resto-app/certs/example.com.jks
      keyStorePassword: 4EVn4tb0wA
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8091

database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:./target/dev;